spring:
  application:
    name: SpringBootTemplate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SnakePC
    username: root
    password: 123456
  redis:
    { database: 1, host: localhost, port: 6379, timeout: 5000 }
  session:
    store-type: redis
    timeout: 2592000
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 接口文档配置
knife4j:
  enable: true
  openapi:
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - fun.timu.init.controller

# 自定义用户空间设置（弃用）
space-level:
  levels:
    common:
      name: "普通版"
      level: 0
      max-images: 100
      max-storage: 104857600  # 100 * 1024 * 1024
    professional:
      name: "专业版"
      level: 1
      max-images: 1000
      max-storage: 1048576000  # 1000 * 1024 * 1024
    flagship:
      name: "旗舰版"
      level: 2
      max-images: 10000
      max-storage: 10485760000  # 10000 * 1024 * 1024
